 import "bootstrap-material-design/dist/css/bootstrap-material-design.css"
import './globals.css'
 

export const metadata = {
  title: 'Next JS learning',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  )
}
