import "bootstrap-material-design/dist/css/bootstrap-material-design.css";
import "./globals.css";
import NavBar from "../../Components/TopNav";
import styles from "../../style/style";

export const metadata = {
  title: "Next JS learning",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className={`${styles.flexCenter} ${styles.paddingX}`}>
          <div className={`${styles.boxWidth}`}>
            <NavBar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
